services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rag_backend
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - rag_network
    restart: unless-stopped
    command: /bin/sh -c "python app.py"
networks:
  rag_network:
    driver: bridge
