services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - rag_network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rag_backend
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - rag_network
    restart: unless-stopped
    command: /bin/sh -c "python app.py"
networks:
  rag_network:
    driver: bridge
